Fix compilation on Linux.
Commit ce15044f7362943aee7d465bf20310ba02991dae introduced an error
"undefined reference to `sball_initialized'" on non-Windows operating
systems.